// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID          int32              `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	Email       string             `db:"email" json:"email"`
	Username    string             `db:"username" json:"username"`
	PhoneNumber pgtype.Text        `db:"phone_number" json:"phone_number"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
